version: '3'
services:
  base_go:
    volumes:
      - ./Webserver/server:/app/server
    environment:
      - ENV=DEV
      - MEILI_URL=http://meilisearch:7700
    container_name: base_go
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Provisioning/go.dev.dockerfile
    tty: true
    ports:
      - "80:80"
    networks:
      - app-network

  # Set up redis - change this name 
  base_go_cache:
    image: "redis:alpine"
    container_name: base_go_cache
    ports:
      - "6379:6379"
    networks:
      - app-network

  # Set up search engine
  meilisearch:
    image: "getmeili/meilisearch"
    container_name: meilisearch
    environment:
      - MEILI_NO_ANALYTICS=true
    ports:
      - "7700:7700"
    networks:
      - app-network

networks:
  app-network:
      driver: bridge