version: '3'
services:
  base_go:
    volumes:
      - ./Webserver/server:/app
    environment:
      - ENV=DEV
    container_name: base_go
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Provisioning/go.dockerfile
    tty: true
    working_dir: /app
    ports:
      - "8080:8080"
    networks:
      - app-network

  # Set up redis - change this name 
  base_go_cache:
    image: "redis:alpine"
    container_name: base_go_cache
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
      driver: bridge