version: '3'
services:
  base_go:
    volumes:
      - ./Webserver/server:/app/server
      - ./Webserver/client/build:/app/client
    environment:
      - ENV=DEV
      - MEILI_URL=http://meilisearch:7700
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=go-search
    container_name: base_go
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Provisioning/go.dev.dockerfile
    tty: true
    depends_on:
      - "redis"
      - "meilisearch"
      - "postgres"
    ports:
      - "80:80"
    networks:
      - app-network

  # Set up redis - change this name 
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  # Set up search engine
  meilisearch:
    image: "getmeili/meilisearch"
    container_name: meilisearch
    environment:
      - MEILI_NO_ANALYTICS=true
    ports:
      - "7700:7700"
    networks:
      - app-network

  # Set up DB
  postgres:
    image: "postgres:14.1-alpine"
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes: 
      - db:/var/lib/postgresql/data
networks:
  app-network:
      driver: bridge
volumes:
  db:
    driver: local