name: Push into Master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        ENV: PROD
      with:
        name: docker.pkg.github.com/tscheuneman/go-search/go-search
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.pkg.github.com
        context: ${{ github.workspace }}
        dockerfile: ${{ github.workspace }}/Provisioning/go.prod.dockerfile